exec-once = [workspace 1 silent] ghostty 
# exec-once = [workspace 2 silent] ghostty --gtk-single-instance=false

exec-once = [workspace 4 silent] discord
exec-once = [workspace 3 silent] zen-browser

exec-once = [workspace 5 silent] spotify
exec-once = [workspace 5 silent] chromium --app=https://web.whatsapp.com
exec-once = solaar -w hide
